### ISSUE TITLE
Handle click/tap action on request markers and show request details

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-help-hybrid#10]
Create handlers to show the info window with all necessary data on clicking on the markers.

**Tasks**
- [ ] Retrieve data from markers
- [ ] Format and display the marker data
- [ ] Add button click/tap handler (_I'm interested to help_) and pass a <request UID ??> to the handler. 

**Additional context**
https://xd.adobe.com/view/b3bd4031-5959-47e0-4b38-da9e6454d57e-c58c/screen/b43e8edd-b687-442a-ba63-fe8e3a9ea696/Volunteer-Home-View-request - p6

![image](https://user-images.githubusercontent.com/4099066/78464405-54583a00-773d-11ea-98b3-7cfd4aa6fd27.png)
