### ISSUE TITLE
Build onboarding slides to be shown on the initial app launch by new users

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-help-hybrid#23]
Build user onboarding screen for initial app users. 

**Tasks**
- [x] Build on boarding pages UI - skip/next buttons, images, text
- [x] Add auto-next after a timeout
- [x] Store onBoardingCompleted flag in device storage and check on every app launch.

**Additional Context**
Use the capacitor storage API as in #20 .
