### ISSUE TITLE
Page to view all requests

### ISSUE THREAD

**Issue by nimishawilson** [Quarantine-Help/quarantine-help-hybrid#36]
Create a page to view all requests

**Tasks**
- [ ] Build a UI as shown in the screenshot.
- [ ] Show open requests and closed requests in separate tabs. 
- [ ] Add cancel and resolve buttons for each request.

**Screenshots**
<img src="https://user-images.githubusercontent.com/49469003/80237122-d02d0e80-8679-11ea-873e-d6269b62ecd9.png" width="50%"/>
