### ISSUE TITLE
Create app menu and implement basic navigation flow

### ISSUE THREAD

**Issue by sebinbenjamin** [Quarantine-Help/quarantine-help-hybrid#42]
**Tasks**
- [ ] Create menu items with icons.
  - Home
  - Advanced search
  - Requests 
  - My Profile
  - Login/ Register
  - Language selection option
- [ ] Implement the menu/open close from the hamburger icon.
- [ ] Link the navigation links to the pages.
