### ISSUE TITLE
Integrate API for resolving and removing a request

### ISSUE THREAD

**Issue by nimishawilson** [Quarantine-Help/quarantine-help-hybrid#65]
Integrate API for resolving and removing a request for HL participant.

**Tasks**
- [x] Add confirmation message when clicking on 'Resolve' button.
- [x] Integrate API for resolving a request - [API for resolving request](http://docs.quarantinehelp.space/#/My%20request-assignments%20for%20a%20HL%20Participant/patch_api_v1_me_assigned_requests__requestId__)
- [x] Change the word 'Cancel' to 'Remove' on the button on the left. 
- [x] When you click on 'Remove' button, add a confirmation message before removing a request.
- [x] Integrate API for removing a request - [API for removing request](http://docs.quarantinehelp.space/#/My%20request-assignments%20for%20a%20HL%20Participant/delete_api_v1_me_assigned_requests__requestId__)

## Screenshots
iPhone X
<img src="https://user-images.githubusercontent.com/4099066/83403070-1127f800-a45c-11ea-89f7-2449c18da896.png" width="50%"/>

Pixel 2 XL
<img src="https://user-images.githubusercontent.com/4099066/83403116-2bfa6c80-a45c-11ea-911e-dada7f573755.png" width="50%"/>

**Additional context**
Related to #57 #43 #49 #64
